{% set version = "1.2-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sciplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sciplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sciplot/sciplot_{{ version }}.tar.gz
  sha256: 738fa4ddc1c1d20f5467376d9278f6461a405617904b871a378e94ade563ff24

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('sciplot')"           # [not win]
    - "\"%R%\" -e \"library('sciplot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sciplot
  license: GPL (>= 2)
  summary: A collection of functions that creates graphs with error bars for data collected from one-way or higher factorial designs.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - conda-forge/r

# Package: sciplot
# Version: 1.1-1
# Title: Scientific Graphing Functions for Factorial Designs
# Author: Manuel Morales <mmorales@williams.edu>, with code developed by the R Development Core Team and with general advice from the R-help listserv community, especially Duncan Murdoch.
# Maintainer: Manuel Morales <Manuel.A.Morales@williams.edu>
# Depends: stats
# Description: A collection of functions that creates graphs with error bars for data collected from one-way or higher factorial designs.
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2017-06-19 21:49:09 UTC; mmorales
# Repository: CRAN
# Date/Publication: 2017-06-19 23:20:32 UTC
