appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: VBV8xXmk1h2YE0LEPolU1ufuYbLxZGz1AN2Qq9n8oKe8DGcJbI8DyO5Jd5a/EVre3+xVCd6tRWyKTWicMgxIflAqmqdVp2jp0H7RHt6J3aqqYFhItl9d/PJG0EpibReY4YYK/2dgsGIkIOwjqEdX63ZpJgVVykLlFWGz3Rg50VhpEY3g8by+V5ZDlKy9pOSkLcDoh6ue0zqCqwosEFv0S98XlF/Yk212jFgNFWYGH4MhDyofTfkkix81Tm8kmO+Xpt0MlGm73WbdR+EYnDARWwSqvlyNeumoSE/z8sXAI43907MbsXKnphlJcU2OPzDwnwC7c6+EJi8yxe9isOWpCq8cHf6uSW1VO0JabDjvc52vGQ0jp4M3mADEDHkO9st/SVCp29La0b64O4Qkf9HMioUlejwz6LNQdYLptBsPw16leae06DQfKyWjOcFYI0SarI5VDBg5eEqZIEdUWNhSBIU0aKUNHF6kikjzUdrkKanpZRTW2F0PafZskMTqg2FONWOy8mp9Q/fnMr0e7R6z9el1txy/5sjle0wcuo308KmrntQhGpjyVwsq90yJzJimZL7e0LnbFyn17okr2+mW5bnLE/mWHdj+gcgoNsgEWS9wIe/dEfyeIm1KqLJClzLoGd/vQAvUa8mNbzBhQj3iX7aAIF/wApqdK6VoLVFZbjI=}
bot:
  automerge: true
